services:
  fastapi:
    build:
      context: .   
      dockerfile: Dockerfile
    container_name: FastApi_b
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1453@localhost:5432/postgres
    volumes:
      - ./:/app
      

  db:
    image: postgres:15
    container_name: FastApi_DB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1453
      - FastApi_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
