services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: "poetry install"
    startCommand: "poetry run uvicorn main:app --host=0.0.0.0 --port=$PORT"
    pythonVersion: 3.13.3
    plan: free