"""Compatibility alias — original bonus panel code used `import storage`."""
from db.sites_storage import *  # noqa: F403
from db.sites_storage import (  # noqa: F401
    add_banner,
    add_board,
    add_category,
    add_popup,
    add_text,
    build_big,
    delete_banner,
    delete_board,
    delete_category,
    delete_popup,
    delete_site,
    delete_text,
    get_banners,
    get_board,
    get_categories,
    get_category,
    get_popups,
    get_texts,
    list_sites,
    load_site,
    save_site,
    update_banner,
    update_board,
    update_category,
    update_popup,
    update_text,
)
